---
title: "Analysis"
subtitle: "My subtitle (optional)"
author: "Name"
date: "`r format(Sys.time(), '%d %b, %Y')`"
---

```{r Dependencies, echo=FALSE, include=FALSE}

pacman::p_load("rmarkdown", "tidyverse", "here", "glue")
knitr::opts_chunk$set(echo = FALSE)

```



```{r Paper Examples}

ex_table3 <- tibble::tibble(id = c("U1", "U2", "U3", "U4"), Obs_F = list(c("b", "d"), c("a", "b", "d"), c(), c("a")), Obs_G = list(c("d"), c("b"), c("a"), NA_character_), Obs_H = list(NA_character_, c("b", "d"), c("a"), NA_character_)) |> tibble::column_to_rownames(var = "id")

mv_alpha(ex_table3, clusters = 2) # 0.2866

ex_table8a <- tibble(id = c(1:3), F = list(c("a"), c("a", "b", "d"), c("d")), G = list(c("a"), c("a", "b", "d"), c("d")), H = list(c("a"), c("a", "b", "d", "e"), c("d"))) |> 
  column_to_rownames("id")

mv_alpha(ex_table8a) # 0.947

ex_table8b <- tibble(id = c(1:3), F = list(c("a"), c("a", "b"), c("d")), G = list(c("a"), c("a", "b"), c("d")), H = list(c("a"), c("a", "b", "d"), c("d"))) |> 
  column_to_rownames("id")

mv_alpha(ex_table8b) # 0.923

ex_table8c <- tibble(id = c(1:3), F = list(c("a"), c("b"), c("d")), G = list(c("a"), c("b"), c("d")), H = list(c("a"), c("b", "d"), c("d"))) |> 
  column_to_rownames("id")

mv_alpha(ex_table8c) # 0.895

ex_table9a <- tibble(id = c(1:3), F = list(c("a"), c("a", "b"), c("d")), G = list(c("a"), c("a", "d"), c("d")), H = list(c("a"), c("d", "b"), c("d"))) |> 
  column_to_rownames("id")

mv_alpha(ex_table9a) # 0.716

ex_table9b <- tibble(id = c(1:3), F = list(c("a"), c("a", "b"), c("d")), G = list(c("a"), c("e", "d"), c("d")), H = list(c("a"), c("f"), c("d"))) |> 
  column_to_rownames("id")

mv_alpha(ex_table9b) # 0.554

ex_table9c <- tibble(id = c(1:3), F = list(c("a"), c("a", "b"), c("b", "d")), G = list(c("b"), c("e", "d"), c("d")), H = list(c("a", "b"), c("f"), c("b", "e"))) |> 
  column_to_rownames("id")

mv_alpha(ex_table9c) # -0.002


```


```{r}

tags <- letters[1:10]

data <- tibble(unit = 1:20) |> 
  rowwise() |> 
  mutate(read1 = list(sample(tags, rpois(1, 1.1) + 1))) |> 
  mutate(read2 = list(sample(tags, rpois(1, 1.1) + 1))) |> 
  column_to_rownames("unit")

```

```{r}

mv_alpha(mvalpha::ex_table3, verbose = TRUE, n_boot = NULL, parallelize = FALSE)
mv_alpha(ex_table3, verbose = FALSE, n_boot = NULL, parallelize = FALSE)
mv_alpha(ex_table3, verbose = TRUE, n_boot = NULL, parallelize = TRUE, cluster_size = 2)
mv_alpha(ex_table3, verbose = FALSE, n_boot = NULL, parallelize = TRUE)
mv_alpha(ex_table3, verbose = TRUE, n_boot = 10, parallelize = FALSE)
mv_alpha(ex_table3, verbose = FALSE, n_boot = 10, parallelize = FALSE)
mv_alpha(ex_table3, verbose = TRUE, n_boot = 10, parallelize = TRUE)
mv_alpha(ex_table3, verbose = FALSE, n_boot = 10, parallelize = TRUE, cluster_size = 6)

mv_alpha(ex_table8b, verbose = TRUE, n_boot = 10, parallelize = FALSE)

```

```{r}


generate_mv_data <- 
  function(n_units = 200, n_readers = 2, n_values = 10, mean_values = 1, se = 0.80, sp = 0.99){
    
    values <- letters[1:n_values]
    latent_label <- lapply(1:n_units, function(i){sample(values, min(rpois(1, mean_values), n_values))})

    data <- 
      lapply(1:n_readers, function(r){
        lapply(latent_label, function(u){
          probs <- c(rep(se, length(u)), rep(1 - sp, n_values - length(u)))
          c(values[which(values %in% u)], values[which(!values %in% u)])[rbinom(n_values, 1, prob = probs) == 1]
        })
      }) |> do.call(cbind, args = _)
    
    dimnames(data) <- list(paste0("obs_", str_pad(1:n_units, width = nchar(n_units), side = "left", pad = "0")), 
                           paste0("read_", str_pad(1:n_readers, width = nchar(n_readers), side = "left", pad = "0")))
    return(data)
  }

test_data <- 
  generate_mv_data()

test_data_ordinal <- 
  tibble(r1 = list(c(1, 2), c(2, 3, 4), c(3, 4), c(1, 3)), 
             r2 = list(c(1, 2), c(2, 3, 4), c(1, 3), c(3, 4)),
             r3 = list(c(1, 2), c(2, 3, 4), c(1, 3), c(3, 4))) |> 
  mutate(id = letters[1:4]) |> 
  column_to_rownames("id")

test_data_single <- 
  tibble(r1 = c(1, 2, 4, 2, 6), 
         r2 = c(1, 2, 3, 4, 6)) |> 
  mutate(id = letters[1:5]) |> 
  column_to_rownames("id")

test_data_ordinal


mvalpha(test_data_single, type = "ordinal")



# apply(test_data, c(1, 2), FUN = function(x){
#   if(length(unlist(x)) > 0){paste0(unlist(x), collapse = "|")}else{"|"}}) |> 
#   data.frame() |> write.csv("test_data.csv", row.names = FALSE)

```

```{r}

# install.packages("tictoc")

tictoc::tic()
new_version <- 
  mvalpha::mv_alpha(test_data, verbose = TRUE, parallelize = FALSE) # 
tictoc::toc() #0.6112317

```


```{r}

a <- 2
f1 <- function(){a}

f2 <- function(b){f1() + b}

test3 <- data.frame(obs_a = c(1, 2, 3, 3, 2, 1, 4, 1, 2, NA, NA, NA),
                    obs_b = c(1, 2, 3, 3, 2, 2, 4, 1, 2, 5, NA, NA),
                    obs_c = c(NA, 3, 3, 3, 2, 3, 4, 2, 2, 5, 1, 3),
                    obs_d = c(1, 2, 3, 3, 2, 4, 4, 1, 2, 5, 1, NA))

test3

```


```{r Save Data and Objects}

# saveRDS(output, here("4. Analysis", glue("{params$nb_id}_output.rds"))) #example

```
